In [9]:
import numpy as np

# Define the arrays
rho = np.array([2, 2, 2, 2])
pow = np.array([1, 2, 1, 2])
pow2 = np.array([[1,2,2,2,],[2,2,2,1]])

# Create an output array of zeros
result = np.zeros_like(rho, dtype=float)
print(result)
print(rho**pow)
print(rho**pow2)

[0. 0. 0. 0.]
[2 4 2 4]
[[2 4 4 4]
 [4 4 4 2]]


In [7]:
# Calculate the power sums grouped by unique power values and add to the original
for p in np.unique(pow):
    indices = np.where(pow == p)  # Find indices where power values match
    result[indices] += rho[indices]**p  # Add the powers of rho to the result at these indices

# Output the result
print("Result:", result) 

Result: [2. 4. 2. 4.]


In [24]:
import numpy as np

# Input vector
V = np.array([1, 1, 2, 3])

# input:   [1, 1, 2, 3] 
# output: [[0, 0, 0, 0],
#          [1, 1, 1, 1], 
#          [0, 0, 2, 2], 
#          [0, 0, 0, 3]]
def column_range_expansion(v:np.array):
    # Determine the number of rows: maximum number in V
    num_rows = np.max(v)
    M = np.zeros((num_rows+1, len(v)), dtype=int)
    for idx, num in enumerate(v):
        M[:num+1, idx] = np.arange(0, num + 1)
    return M

# input: arr: [2, 2, 2, 2]
#        power: [1, 2, 3, 4]
# output: [ 2  6 14 30] = 
#         [2^0+2^1, 2^0+2^1+2^2, 
#           2^0+2^1+2^2+2^3, 2^0+2^1+2^2+2^3+2^4]
def sum_powers(arr:np.array, power:np.array):
    power_expansion = column_range_expansion(power)
    raw_sum = np.sum(arr**power_expansion, axis=0)
    rows_num = power_expansion.shape[0]
    paddings = rows_num - power - 1 # the number of padding zeros
    return raw_sum - paddings 

print(column_range_expansion(V))
# print(column_range_expansion(np.array([2,3,4,5])))
rho = np.array([2,2,2,2])
pow = np.array([1,2,3,4])
print(sum_powers(rho, pow))

[[0 0 0 0]
 [1 1 1 1]
 [0 0 2 2]
 [0 0 0 3]]
[ 3  7 15 31]
